#include "gtest/gtest.h"
#include "AddressMapping.h"
#include "csc/CSCDescriptorEngine.h"
#include "tests/csc/CSCExternalImage.h"
#include "tests/csc/CSCFunctionalModel.h"
#include "tests/csc/CSCLayout.h"
#include <array>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace csc_descriptor;
using DRAMSim::FP32;
namespace{
struct Views{std::array<std::vector<float>,64>x;std::array<CSCBGImageView,64>v;Views(const CSCLayout&l,const std::vector<float>&original){for(uint32_t g=0;g<64;g++){for(auto c:l.bg[g].x_slot_to_original_col)x[g].push_back(original[c]);v[g]={&l.bg[g].values,&l.bg[g].row_indices,&l.bg[g].descriptors,&x[g]};}}};
void invariants(const CSCLayout&l,const CSCExecutionCounters&c){EXPECT_EQ(c.descriptor_fetches,l.stats.descriptor_count);EXPECT_EQ(c.x_scalar_loads,l.stats.descriptor_count);EXPECT_EQ(c.x_transactions,l.stats.descriptor_count);EXPECT_EQ(c.value_transactions,c.total_chunks);EXPECT_EQ(c.index_transactions,c.total_chunks);EXPECT_EQ(c.logical_mul_events,c.total_chunks);EXPECT_EQ(c.full_chunks+c.tail_chunks,c.total_chunks);EXPECT_EQ(c.active_lanes,l.stats.nnz);EXPECT_EQ(c.generated_partials,l.stats.nnz);EXPECT_EQ(c.emitted_partials,l.stats.nnz);EXPECT_EQ(c.host_accumulations,l.stats.nnz);EXPECT_EQ(c.invalid_lane_multiplies,0);EXPECT_EQ(c.invalid_lane_writes,0);if(l.stats.nnz)EXPECT_GT(c.total_execution_cycles,0);}
std::vector<float>run(CSCNativeExecution&native,const CSCLayout&l,const std::vector<float>&x){Views views(l,x);native.launch(views.v,l.matrix.rows,l.stats.nnz);uint64_t guard=0,limit=std::max<uint64_t>(2000000,l.stats.nnz*32);while(!native.done()&&guard++<limit)native.tick();EXPECT_TRUE(native.done())<<"cycle guard="<<limit;if(!native.done())return {};auto y=native.hostAccumulate();invariants(l,native.counters());return y;}
void compare(CSCNativeExecution&native,const CSCMatrix&m,const std::vector<float>&x,MappingPolicy p=MappingPolicy::RoundRobin,const std::vector<uint32_t>&map={}){auto l=buildLayout(m,p,map);auto y=run(native,l,x);auto ref=cpuReference(l.matrix,x);auto old=executeLockstep(l,x);float e;uint32_t r;EXPECT_TRUE(compareResults(ref,y,&e,&r))<<e<<" row "<<r;EXPECT_TRUE(compareResults(old.y,y,&e,&r));}
void expectMalformed(const std::vector<uint8_t>&values,const std::vector<uint8_t>&rows,const std::vector<float>&x,const std::vector<CSCDescriptor>&d){DRAMSim::PIMBlock block(FP32);std::vector<CSCPartial>sink;CSCDescriptorEngine engine(0,&block,[](auto*,auto,auto){return true;},[](auto,auto,auto){return 0;});engine.launch({&values,&rows,&d,&x},&sink);engine.tick();EXPECT_TRUE(engine.isTerminal());EXPECT_TRUE(engine.hasFailed());EXPECT_FALSE(engine.isDone());EXPECT_EQ(engine.errorCode(),CSCError::MALFORMED_DESCRIPTOR);EXPECT_FALSE(engine.errorMessage().empty());}
}
TEST(CSCNativeDescriptorEngineTest,FunctionalBoundariesDescriptorsBGsEmptyAndDuplicates){CSCNativeExecution n;compare(n,makeCSC(0,0,{}),{});for(uint32_t z:{1u,2u,3u,4u,5u,6u,7u,8u,9u,10u,15u,16u,17u}){std::vector<COOEntry>e;for(uint32_t i=0;i<z;i++)e.push_back({i,0,float(i+1)});compare(n,makeCSC(z,1,e),{-2});}auto m=makeCSC(8,6,{{1,0,2},{1,0,3},{2,2,4},{2,3,5},{7,5,6}});compare(n,m,{0,9,-1,2,3,4});std::vector<uint32_t>map(6);map[0]=0;map[2]=0;map[3]=17;map[5]=63;compare(n,m,{0,9,-1,2,3,4},MappingPolicy::External,map);}
TEST(CSCNativeDescriptorEngineTest,FlushResetRelaunchAndTopology){CSCNativeExecution n;auto m=makeCSC(3,2,{{0,0,2},{1,1,3}});auto l=buildLayout(m,MappingPolicy::RoundRobin);Views v(l,{2,4});n.launch(v.v,3,2);n.flush();while(!n.done())n.tick();EXPECT_EQ(n.hostAccumulate(),cpuReference(l.matrix,{2,4}));n.reset();auto y=run(n,l,{2,4});EXPECT_EQ(y,cpuReference(l.matrix,{2,4}));DRAMSim::AddrMapping decode;for(uint32_t g:{0u,1u,17u,63u})for(auto k:{CSCRequestKind::X_READ,CSCRequestKind::VALUE_READ,CSCRequestKind::INDEX_READ}){unsigned ch,r,b,row,col;decode.addressMapping(n.addressFor(g,k,0),ch,r,b,row,col);EXPECT_EQ(ch,g/4);EXPECT_EQ(decode.bankgroupId(b),g%4);}}
TEST(CSCNativeDescriptorEngineTest,BackpressureAndMalformedDescriptors){DRAMSim::PIMBlock block(FP32);std::vector<uint8_t>values(64),rows(64);float one=1;uint32_t row=0;std::memcpy(values.data(),&one,4);std::memcpy(rows.data(),&row,4);std::vector<float>x{2};std::vector<CSCDescriptor>d{{0,0,1,0,0,0}};std::vector<CSCPartial>sink;int reject=3;uint64_t addr=0;CSCDescriptorEngine e(0,&block,[&](auto*,auto,uint64_t a){addr=a;if(reject){reject--;return false;}return true;},[](auto,auto,uint64_t o){return o+32;});e.launch({&values,&rows,&d,&x},&sink);for(int i=0;i<200&&!e.done();i++){e.tick();if(e.tracker().pending())e.onRequestComplete(0,addr,i);}EXPECT_TRUE(e.done());EXPECT_GE(e.counters().stall_cycles_backpressure,3);e.reset();auto bad=d;bad[0].value_offset_bytes=4;expectMalformed(values,rows,x,bad);bad=d;bad[0].global_bg_id=1;expectMalformed(values,rows,x,bad);bad=d;bad[0].x_slot=1;expectMalformed(values,rows,x,bad);bad=d;bad[0].nnz_count=17;expectMalformed(values,rows,x,bad);}
TEST(CSCNativeDescriptorEngineIntegrationTest,ExternalImageMatchesAuthoritativeFP32){const char*p=std::getenv("CSC_EXTERNAL_IMAGE");if(!p||!*p)GTEST_SKIP()<<"set CSC_EXTERNAL_IMAGE";auto l=loadExternalPhysicalImage(p).layout;std::vector<float>x(l.matrix.cols);for(uint32_t i=0;i<x.size();i++)x[i]=float((i%13)+1)/7;CSCNativeExecution n;auto y=run(n,l,x),ref=cpuReference(l.matrix,x);float e;uint32_t r;EXPECT_TRUE(compareResults(ref,y,&e,&r))<<e<<" row "<<r;}
TEST(CSCNativeDescriptorEngineTest,ValidXNaNAndInfUseIEEEPropagation){auto l=buildLayout(makeCSC(1,1,{{0,0,2}}),MappingPolicy::RoundRobin);CSCNativeExecution nan_engine;auto nan_y=run(nan_engine,l,{NAN});ASSERT_EQ(nan_y.size(),1);EXPECT_TRUE(std::isnan(nan_y[0]));CSCNativeExecution inf_engine;auto inf_y=run(inf_engine,l,{INFINITY});ASSERT_EQ(inf_y.size(),1);EXPECT_TRUE(std::isinf(inf_y[0]));}
TEST(CSCNativeDescriptorEngineTest,ErrorIsTerminalAndPropagatesGlobally){
 CSCNativeExecution n;auto l=buildLayout(makeCSC(2,1,{{0,0,2},{1,0,3}}),MappingPolicy::RoundRobin);Views v(l,{4});n.launch(v.v,2,2);l.bg[0].descriptors[0].value_offset_bytes=4;uint64_t guard=0;while(!n.done()&&guard++<10000)n.tick();EXPECT_LT(guard,10000);EXPECT_TRUE(n.isTerminal());EXPECT_TRUE(n.hasFailed());EXPECT_FALSE(n.isDone());EXPECT_EQ(n.failedEngine(),0);EXPECT_EQ(n.errorCode(),CSCError::MALFORMED_DESCRIPTOR);EXPECT_FALSE(n.errorMessage().empty());EXPECT_FALSE(n.hasOutstandingRequest());EXPECT_FALSE(n.hasPendingTransactions());EXPECT_FALSE(n.hasUnconsumedCompletion());EXPECT_THROW(n.hostAccumulate(),std::logic_error);n.flush();EXPECT_TRUE(n.hasFailed());EXPECT_FALSE(n.isDone());n.reset();EXPECT_FALSE(n.isTerminal());l.bg[0].descriptors[0].value_offset_bytes=0;EXPECT_EQ(run(n,l,{4}),cpuReference(l.matrix,{4}));
}
TEST(CSCNativeDescriptorEngineTest,FailureWhileRequestPendingDrainsWithoutNewIssue){
 CSCNativeExecution n;auto l=buildLayout(makeCSC(1,1,{{0,0,2}}),MappingPolicy::RoundRobin);Views v(l,{4});n.launch(v.v,1,1);uint64_t guard=0;while(!n.engine(0).tracker().pending()&&guard++<1000)n.tick();ASSERT_TRUE(n.engine(0).tracker().pending());auto issued=n.engine(0).tracker().stats().issued;v.x[0].clear();while(!n.done()&&guard++<10000)n.tick();ASSERT_TRUE(n.isTerminal());EXPECT_TRUE(n.hasFailed());EXPECT_FALSE(n.hasOutstandingRequest());EXPECT_FALSE(n.hasPendingTransactions());EXPECT_FALSE(n.hasUnconsumedCompletion());for(int i=0;i<20;i++)n.tick();EXPECT_EQ(n.engine(0).tracker().stats().issued,issued);n.reset();Views valid(l,{4});n.launch(valid.v,1,1);while(!n.done()&&guard++<20000)n.tick();EXPECT_TRUE(n.isDone());
}
TEST(CSCNativeDescriptorEngineTest,GracefulFlushCoversStatesAndRelaunch){
 const std::array<CSCDescriptorState,6> states={CSCDescriptorState::LOAD_X,CSCDescriptorState::FETCH_VALUE,CSCDescriptorState::FETCH_ROW_INDEX,CSCDescriptorState::SIMD_MUL,CSCDescriptorState::EMIT_PARTIALS,CSCDescriptorState::NEXT_DESCRIPTOR};
 for(auto target:states){CSCNativeExecution n;auto l=buildLayout(makeCSC(12,2,{{0,0,2},{1,0,3},{2,0,4},{3,0,5},{4,0,6},{5,0,7},{6,0,8},{7,0,9},{8,0,10},{9,1,11},{10,1,12},{11,1,13}}),MappingPolicy::RoundRobin);Views v(l,{2,3});n.launch(v.v,12,12);uint64_t guard=0;while(n.engine(0).state()!=target&&guard++<100000)n.tick();ASSERT_LT(guard,100000);n.flush();n.flush();EXPECT_TRUE(n.flushRequested());while(!n.done()&&guard++<300000)n.tick();ASSERT_TRUE(n.isDone());EXPECT_TRUE(n.flushComplete());EXPECT_FALSE(n.hasFailed());EXPECT_FALSE(n.hasOutstandingRequest());EXPECT_FALSE(n.hasPendingTransactions());EXPECT_FALSE(n.hasUnconsumedCompletion());EXPECT_EQ(n.counters().generated_partials,n.counters().emitted_partials);EXPECT_EQ(n.hostAccumulate(),cpuReference(l.matrix,{2,3}));n.reset();EXPECT_EQ(run(n,l,{2,3}),cpuReference(l.matrix,{2,3}));}
 CSCNativeExecution idle;idle.flush();EXPECT_TRUE(idle.flushRequested());idle.tick();EXPECT_TRUE(idle.isDone());EXPECT_TRUE(idle.flushComplete());idle.flush();EXPECT_TRUE(idle.isDone());
}
