#include "gtest/gtest.h"
#include "tests/csc/CSCFunctionalModel.h"
#include "tests/csc/CSCTimingModel.h"
#include <numeric>
using namespace csc_descriptor;
namespace {
std::vector<float> makeX(uint32_t n){std::vector<float>x(n);for(uint32_t i=0;i<n;++i)x[i]=float((i%13)+1)/7;return x;}
void check(const CSCMatrix&m,MappingPolicy p=MappingPolicy::RoundRobin,const std::vector<uint32_t>&map={}){auto l=buildLayout(m,p,map);auto x=makeX(m.cols);auto ref=cpuReference(m,x);auto got=executeLockstep(l,x);float err;uint32_t row;EXPECT_TRUE(compareResults(ref,got.y,&err,&row))<<"max_error="<<err<<" row="<<row;EXPECT_EQ(l.stats.nnz,m.values.size());EXPECT_EQ(l.stats.descriptor_count,l.stats.nonempty_columns);EXPECT_EQ(got.stats.generated_partial_count,m.values.size());EXPECT_EQ(got.stats.host_accumulation_count,m.values.size());for(auto&b:l.bg)for(auto&d:b.descriptors){EXPECT_EQ(d.value_offset_bytes%32,0);EXPECT_EQ(d.row_idx_offset_bytes%32,0);EXPECT_EQ((d.nnz_count+7)/8,std::count_if(got.stats.bg_chunk_count.begin(),got.stats.bg_chunk_count.end(),[](auto){return false;})+(d.nnz_count+7)/8);}}
}
TEST(CSCDescriptorFunctionalTest, EmptyMatrixAndEmptyColumns){check(makeCSC(0,0,{}));check(makeCSC(4,6,{{1,2,3},{3,5,2}}));}
TEST(CSCDescriptorFunctionalTest, RequiredTailLengths){for(uint32_t n:{1u,7u,8u,9u,15u,16u,17u}){std::vector<COOEntry>e;for(uint32_t i=0;i<n;++i)e.push_back({i,0,float(i+1)});auto m=makeCSC(n,1,e);auto l=buildLayout(m,MappingPolicy::RoundRobin);auto f=executeLockstep(l,makeX(1));EXPECT_EQ(f.stats.total_chunks,(n+7)/8);EXPECT_EQ(f.stats.active_lanes,n);EXPECT_EQ(f.stats.generated_partial_count,n);check(m);}}
TEST(CSCDescriptorFunctionalTest, DuplicatesAndSharedOutputRows){check(makeCSC(3,4,{{1,0,2},{1,0,3},{1,1,4},{1,2,5},{1,3,6}}));}
TEST(CSCDescriptorFunctionalTest, RawOffsetsFourTwelveTwentyEightBecomeAligned){auto m=makeCSC(32,4,{{0,0,1},{1,1,1},{2,1,1},{3,1,1},{4,2,1},{5,2,1},{6,2,1},{7,2,1},{8,2,1},{9,2,1},{10,2,1},{11,3,1}});std::vector<uint32_t>map(4,0);auto l=buildLayout(m,MappingPolicy::External,map);ASSERT_EQ(l.bg[0].descriptors.size(),4);for(auto&d:l.bg[0].descriptors){EXPECT_EQ(d.value_offset_bytes%32,0);EXPECT_EQ(d.row_idx_offset_bytes%32,0);}EXPECT_GT(l.stats.total_alignment_padding_bytes,0);check(m,MappingPolicy::External,map);}
TEST(CSCDescriptorFunctionalTest, ExternalAllColumnsOneBGAndSmallDimension){auto m=makeCSC(8,3,{{0,0,1},{0,1,2},{0,2,3}});std::vector<uint32_t>map(3,63);auto l=buildLayout(m,MappingPolicy::External,map);EXPECT_EQ(l.bg[63].descriptors.size(),3);for(uint32_t g=0;g<63;++g)EXPECT_TRUE(l.bg[g].descriptors.empty());check(m,MappingPolicy::External,map);}
TEST(CSCDescriptorFunctionalTest, RoundRobinUsesAll64BGs){std::vector<COOEntry>e;for(uint32_t c=0;c<64;++c)e.push_back({c,c,1});auto l=buildLayout(makeCSC(64,64,e),MappingPolicy::RoundRobin);for(auto&b:l.bg)EXPECT_EQ(b.descriptors.size(),1);check(l.matrix);}
TEST(CSCDescriptorTimingTest, TopologyAndSeparatedPhases){auto m=makeCSC(8,3,{{0,0,1},{1,0,2},{2,1,3},{3,2,4},{4,2,5},{5,2,6},{6,2,7},{7,2,8}});auto l=buildLayout(m,MappingPolicy::RoundRobin);auto f=executeLockstep(l,makeX(3));CSCTimingModel timing;EXPECT_EQ(timing.globalBGCount(),64);auto s=timing.run(l,f.stats);EXPECT_GT(s.matrix_preload_cycles,0);EXPECT_GT(s.x_load_cycles,0);EXPECT_GT(s.value_read_cycles,0);EXPECT_GT(s.row_index_read_cycles,0);EXPECT_EQ(s.kernel_resident_cycles,s.value_read_cycles+s.row_index_read_cycles+s.result_cycles);EXPECT_EQ(s.end_to_end_simulated_cycles,s.matrix_preload_cycles+s.kernel_with_x_cycles);}
