#include "tests/csc/CSCExternalImage.h"
#include <algorithm>
#include <cmath>
#include <cstring>
#include <fstream>
#include <iomanip>
#include <limits>
#include <sstream>
#include <stdexcept>
namespace csc_descriptor {namespace {
std::string readText(const std::string&p){std::ifstream f(p);if(!f)throw std::runtime_error("missing "+p);return std::string(std::istreambuf_iterator<char>(f),{});}
std::vector<uint8_t>readBytes(const std::string&p){std::ifstream f(p,std::ios::binary);if(!f)throw std::runtime_error("missing "+p);return std::vector<uint8_t>(std::istreambuf_iterator<char>(f),{});}
size_t valueAt(const std::string&j,const std::string&k){std::string q="\""+k+"\"";size_t p=j.find(q);if(p==std::string::npos)throw std::runtime_error("manifest missing "+k);p=j.find(':',p+q.size());if(p==std::string::npos)throw std::runtime_error("manifest syntax "+k);return p+1;}
std::string stringValue(const std::string&j,const std::string&k){size_t p=valueAt(j,k);p=j.find('"',p);size_t e=p==std::string::npos?p:j.find('"',p+1);if(p==std::string::npos||e==std::string::npos)throw std::runtime_error("manifest string "+k);return j.substr(p+1,e-p-1);}
double numberValue(const std::string&j,const std::string&k){size_t p=valueAt(j,k),used=0;double v=std::stod(j.substr(p),&used);if(!used)throw std::runtime_error("manifest number "+k);return v;}
uint64_t uintValue(const std::string&j,const std::string&k){double d=numberValue(j,k);if(d<0||d>double(std::numeric_limits<uint64_t>::max())||std::floor(d)!=d)throw std::runtime_error("manifest integer "+k);return static_cast<uint64_t>(d);}
std::string arrayBody(const std::string&j,const std::string&k){size_t p=j.find('[',valueAt(j,k)),e=p==std::string::npos?p:j.find(']',p);if(p==std::string::npos||e==std::string::npos)throw std::runtime_error("manifest array "+k);return j.substr(p+1,e-p-1);}
std::vector<uint64_t>uintArray(const std::string&j,const std::string&k){std::string b=arrayBody(j,k);std::vector<uint64_t>v;std::stringstream s(b);while(s){s>>std::ws;if(s.peek()==EOF)break;uint64_t x;if(!(s>>x))throw std::runtime_error("manifest uint array "+k);v.push_back(x);s>>std::ws;if(s.peek()==',')s.get();else if(s.peek()!=EOF)throw std::runtime_error("manifest uint separator "+k);}return v;}
std::vector<std::string>stringArray(const std::string&j,const std::string&k){std::string b=arrayBody(j,k);std::vector<std::string>v;size_t p=0;while((p=b.find('"',p))!=std::string::npos){size_t e=b.find('"',p+1);if(e==std::string::npos)throw std::runtime_error("manifest string array "+k);v.push_back(b.substr(p+1,e-p-1));p=e+1;}return v;}
uint32_t u32(const std::vector<uint8_t>&b,size_t p){if(p+4>b.size())throw std::runtime_error("truncated uint32");uint32_t v=0;for(int i=0;i<4;++i)v|=uint32_t(b[p+i])<<(8*i);return v;}
uint64_t u64(const std::vector<uint8_t>&b,size_t p){if(p+8>b.size())throw std::runtime_error("truncated uint64");uint64_t v=0;for(int i=0;i<8;++i)v|=uint64_t(b[p+i])<<(8*i);return v;}
uint64_t fnv(const std::vector<uint8_t>&b){uint64_t h=0xcbf29ce484222325ULL;for(uint8_t x:b){h^=x;h*=0x100000001b3ULL;}return h;}
std::string hex64(uint64_t v){std::ostringstream s;s<<std::hex<<std::nouppercase<<std::setw(16)<<std::setfill('0')<<v;return s.str();}
std::string prefix(const std::string&dir,uint32_t g){std::ostringstream s;s<<dir<<"/bg_"<<std::setw(2)<<std::setfill('0')<<g;return s.str();}
void require64(size_t n,const std::string&name){if(n!=64)throw std::runtime_error(name+" must have 64 entries");}
}
ExternalImage loadExternalPhysicalImage(const std::string&dir){
 std::string j=readText(dir+"/manifest.json");
 if(stringValue(j,"format_magic")!="SPCSCIMG"||uintValue(j,"format_version")!=1||stringValue(j,"endianness")!="little"||stringValue(j,"precision")!="FP32"||stringValue(j,"output_value_type")!="float32"||stringValue(j,"row_index_type")!="uint32"||stringValue(j,"offset_type")!="uint64"||uintValue(j,"alignment_bytes")!=32||uintValue(j,"num_global_bgs")!=64||uintValue(j,"descriptor_record_bytes")!=32||uintValue(j,"segment_nnz")!=0)throw std::runtime_error("unsupported CSC image contract");
 uint64_t rows=uintValue(j,"matrix_rows"),cols=uintValue(j,"matrix_columns"),nnz=uintValue(j,"matrix_nnz");if(rows>UINT32_MAX||cols>UINT32_MAX)throw std::runtime_error("matrix dimensions exceed uint32");
 auto dc=uintArray(j,"bg_descriptor_counts"),vs=uintArray(j,"bg_value_stream_bytes"),rs=uintArray(j,"bg_row_index_stream_bytes"),xc=uintArray(j,"bg_x_permutation_counts"),owners=uintArray(j,"column_to_bg");
 auto vh=stringArray(j,"bg_values_fnv1a64"),rh=stringArray(j,"bg_row_idx_fnv1a64"),dh=stringArray(j,"bg_descriptors_fnv1a64"),xh=stringArray(j,"bg_x_permutation_fnv1a64");
 require64(dc.size(),"descriptor counts");require64(vs.size(),"value sizes");require64(rs.size(),"row sizes");require64(xc.size(),"x counts");require64(vh.size(),"value checksums");require64(rh.size(),"row checksums");require64(dh.size(),"descriptor checksums");require64(xh.size(),"x checksums");if(owners.size()!=cols)throw std::runtime_error("column owner count mismatch");
 ExternalImage out;auto&l=out.layout;l.source=LayoutSource::ExternalPhysicalImage;l.mapping_policy=stringValue(j,"mapping_policy")=="round_robin"?MappingPolicy::RoundRobin:MappingPolicy::External;l.column_to_bg.resize(cols);for(size_t c=0;c<owners.size();++c){if(owners[c]>=64)throw std::runtime_error("column owner outside [0,63]");l.column_to_bg[c]=owners[c];}l.bg.resize(64);
 std::vector<std::vector<uint32_t>> col_rows(cols);std::vector<std::vector<float>> col_values(cols);std::vector<uint8_t>seen(cols);
 for(uint32_t g=0;g<64;++g){std::string p=prefix(dir,g);auto values=readBytes(p+"_values.bin"),row=readBytes(p+"_row_idx.bin"),desc=readBytes(p+"_descriptors.bin"),x=readBytes(p+"_x_permutation.bin");if(values.size()!=vs[g]||row.size()!=rs[g]||desc.size()!=dc[g]*32||x.size()!=xc[g]*4||dc[g]!=xc[g])throw std::runtime_error("external image file size invariant");if(hex64(fnv(values))!=vh[g]||hex64(fnv(row))!=rh[g]||hex64(fnv(desc))!=dh[g]||hex64(fnv(x))!=xh[g])throw std::runtime_error("external image checksum invariant");auto&bg=l.bg[g];bg.values=std::move(values);bg.row_indices=std::move(row);for(uint64_t i=0;i<xc[g];++i)bg.x_slot_to_original_col.push_back(u32(x,i*4));std::vector<uint8_t>usedv(bg.values.size()),usedr(bg.row_indices.size());for(uint64_t i=0;i<dc[g];++i){size_t at=i*32;CSCDescriptor d{u64(desc,at),u64(desc,at+8),u32(desc,at+16),u32(desc,at+20),u32(desc,at+24),u32(desc,at+28)};if(d.global_bg_id!=g||d.x_slot!=i||d.x_slot>=bg.x_slot_to_original_col.size()||bg.x_slot_to_original_col[d.x_slot]!=d.original_col||d.original_col>=cols||l.column_to_bg[d.original_col]!=g||!d.nnz_count||d.value_offset_bytes%32||d.row_idx_offset_bytes%32||d.value_offset_bytes+uint64_t(d.nnz_count)*4>bg.values.size()||d.row_idx_offset_bytes+uint64_t(d.nnz_count)*4>bg.row_indices.size()||seen[d.original_col]++)throw std::runtime_error("external descriptor invariant");for(uint32_t q=0;q<d.nnz_count;++q){size_t vo=d.value_offset_bytes+uint64_t(q)*4,ro=d.row_idx_offset_bytes+uint64_t(q)*4;uint32_t bits=u32(bg.values,vo),r=u32(bg.row_indices,ro);if(r>=rows)throw std::runtime_error("external row index range");float value;std::memcpy(&value,&bits,4);col_values[d.original_col].push_back(value);col_rows[d.original_col].push_back(r);for(size_t k=0;k<4;++k){usedv[vo+k]=1;usedr[ro+k]=1;}}bg.descriptors.push_back(d);}for(size_t i=0;i<bg.values.size();++i)if(!usedv[i]&&bg.values[i])throw std::runtime_error("external value padding is not zero");for(size_t i=0;i<bg.row_indices.size();++i)if(!usedr[i]&&bg.row_indices[i])throw std::runtime_error("external row padding is not zero");}
 l.matrix.rows=rows;l.matrix.cols=cols;l.matrix.col_ptr.assign(cols+1,0);for(uint32_t c=0;c<cols;++c){if(seen[c]!=(col_values[c].empty()?0:1))throw std::runtime_error("external column ownership invariant");l.matrix.col_ptr[c+1]=l.matrix.col_ptr[c]+col_values[c].size();l.matrix.values.insert(l.matrix.values.end(),col_values[c].begin(),col_values[c].end());l.matrix.row_idx.insert(l.matrix.row_idx.end(),col_rows[c].begin(),col_rows[c].end());}if(l.matrix.values.size()!=nnz)throw std::runtime_error("external NNZ invariant");refreshLayoutStats(l);validateLayout(l);
 auto&m=out.metadata;m.mapping_policy=stringValue(j,"mapping_policy");m.input_value_type=stringValue(j,"input_value_type");m.output_value_type=stringValue(j,"output_value_type");m.fp32_conversion_count=uintValue(j,"fp32_conversion_count");m.nan_count=uintValue(j,"nan_count");m.inf_count=uintValue(j,"inf_count");m.fp32_conversion_ms=numberValue(j,"fp32_conversion_ms");m.aligned_materialization_ms=numberValue(j,"aligned_materialization_ms");m.metadata_generation_ms=numberValue(j,"metadata_generation_ms");m.validation_ms=numberValue(j,"validation_ms");m.checksum_ms=numberValue(j,"checksum_ms");m.serialization_ms=numberValue(j,"serialization_ms");m.file_write_ms=numberValue(j,"file_write_ms");if(m.fp32_conversion_count!=nnz)throw std::runtime_error("FP32 conversion count invariant");return out;
}
}
