#include "gtest/gtest.h"
#include "tests/csc/CSCExternalImage.h"
#include "tests/csc/CSCFunctionalModel.h"
#include "tests/csc/CSCTimingModel.h"
#include <cstdlib>
using namespace csc_descriptor;
namespace {
std::string requiredEnv(const char*name){const char*v=std::getenv(name);return v?v:"";}
std::vector<float> testX(uint32_t n){std::vector<float>x(n);for(uint32_t i=0;i<n;++i)x[i]=float((i%13)+1)/7;return x;}
void expectDescriptor(const CSCDescriptor&a,const CSCDescriptor&b){EXPECT_EQ(a.value_offset_bytes,b.value_offset_bytes);EXPECT_EQ(a.row_idx_offset_bytes,b.row_idx_offset_bytes);EXPECT_EQ(a.nnz_count,b.nnz_count);EXPECT_EQ(a.x_slot,b.x_slot);EXPECT_EQ(a.original_col,b.original_col);EXPECT_EQ(a.global_bg_id,b.global_bg_id);}
void expectAccounting(const CSCLayout&l,const ExecutionStats&s){EXPECT_EQ(s.active_lanes,l.stats.nnz);EXPECT_EQ(s.generated_partial_count,l.stats.nnz);EXPECT_EQ(s.host_accumulation_count,l.stats.nnz);EXPECT_EQ(s.invalid_lane_multiplication_count,0);EXPECT_EQ(s.invalid_lane_partial_count,0);EXPECT_EQ(s.invalid_lane_accumulation_count,0);EXPECT_EQ(s.value_burst_read_count,s.total_chunks);EXPECT_EQ(s.row_index_burst_read_count,s.total_chunks);EXPECT_EQ(s.logical_csc_mul_events,s.total_chunks);EXPECT_EQ(s.x_scalar_load_count,l.stats.descriptor_count);EXPECT_EQ(s.required_unique_x_bursts,s.actual_issued_x_transactions);}
}
TEST(CSCExternalImageFunctionalTest,ToyRoundTripMatchesInternalBuilderByteForByte){std::string image=requiredEnv("CSC_EXTERNAL_IMAGE");std::string matrix=requiredEnv("CSC_EXTERNAL_MATRIX");if(image.empty()||matrix.empty())GTEST_SKIP()<<"set CSC_EXTERNAL_IMAGE and CSC_EXTERNAL_MATRIX";auto loaded=loadExternalPhysicalImage(image);auto internal=buildLayout(loadCSC(matrix),MappingPolicy::RoundRobin);auto&external=loaded.layout;ASSERT_EQ(external.source,LayoutSource::ExternalPhysicalImage);ASSERT_EQ(internal.matrix.rows,external.matrix.rows);ASSERT_EQ(internal.matrix.cols,external.matrix.cols);ASSERT_EQ(internal.matrix.col_ptr,external.matrix.col_ptr);ASSERT_EQ(internal.matrix.row_idx,external.matrix.row_idx);ASSERT_EQ(internal.matrix.values,external.matrix.values);ASSERT_EQ(internal.column_to_bg,external.column_to_bg);for(uint32_t g=0;g<64;++g){EXPECT_EQ(internal.bg[g].values,external.bg[g].values)<<"BG "<<g;EXPECT_EQ(internal.bg[g].row_indices,external.bg[g].row_indices)<<"BG "<<g;EXPECT_EQ(internal.bg[g].x_slot_to_original_col,external.bg[g].x_slot_to_original_col)<<"BG "<<g;ASSERT_EQ(internal.bg[g].descriptors.size(),external.bg[g].descriptors.size())<<"BG "<<g;for(size_t i=0;i<internal.bg[g].descriptors.size();++i)expectDescriptor(internal.bg[g].descriptors[i],external.bg[g].descriptors[i]);}EXPECT_EQ(internal.stats.descriptor_count,external.stats.descriptor_count);EXPECT_EQ(internal.stats.useful_value_bytes,external.stats.useful_value_bytes);EXPECT_EQ(internal.stats.value_alignment_padding_bytes,external.stats.value_alignment_padding_bytes);EXPECT_EQ(internal.stats.physical_value_bytes,external.stats.physical_value_bytes);EXPECT_EQ(internal.stats.useful_index_bytes,external.stats.useful_index_bytes);EXPECT_EQ(internal.stats.index_alignment_padding_bytes,external.stats.index_alignment_padding_bytes);EXPECT_EQ(internal.stats.physical_index_bytes,external.stats.physical_index_bytes);auto x=testX(external.matrix.cols),ref=cpuReference(external.matrix,x);auto a=executeLockstep(internal,x),b=executeLockstep(external,x);float err;uint32_t row;EXPECT_TRUE(compareResults(ref,a.y,&err,&row));EXPECT_TRUE(compareResults(ref,b.y,&err,&row));EXPECT_EQ(a.y,b.y);EXPECT_EQ(a.stats.total_chunks,b.stats.total_chunks);expectAccounting(external,b.stats);EXPECT_EQ(loaded.metadata.input_value_type,"float64");EXPECT_EQ(loaded.metadata.output_value_type,"float32");EXPECT_EQ(loaded.metadata.fp32_conversion_count,external.stats.nnz);}
TEST(CSCExternalImageTimingTest,ToyTopologyAndAccounting){std::string image=requiredEnv("CSC_EXTERNAL_IMAGE");if(image.empty())GTEST_SKIP()<<"set CSC_EXTERNAL_IMAGE";auto external=loadExternalPhysicalImage(image).layout;auto x=testX(external.matrix.cols);auto f=executeLockstep(external,x);expectAccounting(external,f.stats);CSCTimingModel timing;EXPECT_NO_THROW(timing.validateTopologyAddresses(external));auto s=timing.run(external,f.stats,ResultTrafficMode::None);EXPECT_EQ(s.value_bursts,f.stats.total_chunks);EXPECT_EQ(s.row_index_bursts,f.stats.total_chunks);EXPECT_EQ(s.x_bursts,f.stats.required_unique_x_bursts);EXPECT_EQ(s.result_bursts,0);EXPECT_EQ(s.result_cycles,0);}
