#include "tests/csc/CSCFunctionalModel.h"
#include <algorithm>
#include <chrono>
#include <cmath>
#include <cstring>
#include <stdexcept>
namespace csc_descriptor {using Clock=std::chrono::steady_clock;
std::vector<float>cpuReference(const CSCMatrix&m,const std::vector<float>&x){if(x.size()!=m.cols)throw std::invalid_argument("x size");std::vector<double>sum(m.rows);for(uint32_t c=0;c<m.cols;++c)for(uint64_t p=m.col_ptr[c];p<m.col_ptr[c+1];++p)sum[m.row_idx[p]]+=double(m.values[p]*x[c]);std::vector<float>y(m.rows);for(size_t i=0;i<y.size();++i)y[i]=float(sum[i]);return y;}
struct Worker{size_t descriptor=0;uint32_t consumed=0;};
FunctionalResult executeLockstep(const CSCLayout&l,const std::vector<float>&x){validateLayout(l);if(x.size()!=l.matrix.cols)throw std::invalid_argument("x size");FunctionalResult o;o.y.assign(l.matrix.rows,0);o.x_packed.resize(64);auto t=Clock::now();for(uint32_t g=0;g<64;++g){for(auto c:l.bg[g].x_slot_to_original_col)o.x_packed[g].push_back(x[c]);o.stats.x_burst_read_count+=(o.x_packed[g].size()+7)/8;}o.stats.x_packing_wall_ms=std::chrono::duration<double,std::milli>(Clock::now()-t).count();o.stats.bg_chunk_count.assign(64,0);o.stats.bg_idle_round_count.assign(64,0);std::vector<Worker>w(64);std::vector<std::pair<uint32_t,float>>parts;parts.reserve(l.matrix.values.size());t=Clock::now();
 while(true){bool any=false;for(uint32_t g=0;g<64;++g){auto&im=l.bg[g];auto&z=w[g];if(z.descriptor>=im.descriptors.size())continue;any=true;auto&d=im.descriptors[z.descriptor];if(!z.consumed){o.stats.x_scalar_load_count++;}uint32_t valid=std::min<uint32_t>(d.nnz_count-z.consumed,8);float vals[8]{};uint32_t rows[8]{};std::memcpy(vals,im.values.data()+d.value_offset_bytes+z.consumed*4,valid*4);std::memcpy(rows,im.row_indices.data()+d.row_idx_offset_bytes+z.consumed*4,valid*4);float scalar=o.x_packed[g][d.x_slot];for(uint32_t lane=0;lane<valid;++lane)parts.push_back({rows[lane],vals[lane]*scalar});o.stats.total_chunks++;o.stats.bg_chunk_count[g]++;o.stats.active_lanes+=valid;o.stats.total_available_lanes+=8;o.stats.logical_csc_mul_events++;o.stats.value_burst_read_count++;o.stats.row_index_burst_read_count++;o.stats.generated_partial_count+=valid;valid==8?o.stats.full_chunks++:o.stats.tail_chunks++;z.consumed+=valid;if(z.consumed==d.nnz_count){z.descriptor++;z.consumed=0;}}if(!any)break;o.stats.total_lockstep_rounds++;}
 o.stats.multiplication_wall_ms=std::chrono::duration<double,std::milli>(Clock::now()-t).count();t=Clock::now();std::vector<double>sum(o.y.size());for(auto&p:parts){if(p.first>=o.y.size())throw std::logic_error("row range");sum[p.first]+=double(p.second);o.stats.host_accumulation_count++;}for(size_t i=0;i<o.y.size();++i)o.y[i]=float(sum[i]);o.stats.host_accumulation_wall_ms=std::chrono::duration<double,std::milli>(Clock::now()-t).count();o.stats.simd_lane_utilization=o.stats.total_available_lanes?double(o.stats.active_lanes)/o.stats.total_available_lanes:0;o.stats.critical_bg=std::distance(o.stats.bg_chunk_count.begin(),std::max_element(o.stats.bg_chunk_count.begin(),o.stats.bg_chunk_count.end()));for(uint32_t g=0;g<64;++g)o.stats.bg_idle_round_count[g]=o.stats.total_lockstep_rounds-o.stats.bg_chunk_count[g];return o;}
 bool compareResults(const std::vector<float>&r,const std::vector<float>&a,float*maxe,uint32_t*first){if(r.size()!=a.size())return false;float mx=0;uint32_t f=UINT32_MAX;for(uint32_t i=0;i<r.size();++i){float e=std::fabs(a[i]-r[i]);mx=std::max(mx,e);if(f==UINT32_MAX&&e>kAbsoluteTolerance+kRelativeTolerance*std::fabs(r[i]))f=i;}if(maxe)*maxe=mx;if(first)*first=f;return f==UINT32_MAX;}
}
