#include "tests/csc/CSCTimingModel.h"
#include "SystemConfiguration.h"
#include <stdexcept>
namespace csc_descriptor {
CSCTimingModel::CSCTimingModel(){mem_=std::make_shared<DRAMSim::MultiChannelMemorySystem>("ini/HBM2_samsung_2M_16B_x64.ini","system_hbm_csc_fp32.ini",".","csc_descriptor",256*kChannels);channels_=getConfigParam(UINT,"NUM_CHANS");ranks_=getConfigParam(UINT,"NUM_RANKS");bgs_=getConfigParam(UINT,"NUM_BANK_GROUPS");banks_=getConfigParam(UINT,"NUM_BANKS");if(channels_!=16||ranks_!=1||bgs_!=4||banks_/bgs_!=4||channels_*ranks_*bgs_!=64||getConfigParam(UINT,"BL")*getConfigParam(UINT,"JEDEC_DATA_BUS_BITS")/8!=32||PIMConfiguration::getPIMPrecision()!=FP32)throw std::runtime_error("CSC requires 16ch/1rank/4BG/4bank-per-BG/32B/FP32");am_=std::make_shared<PIMAddrManager>(channels_,ranks_);}
uint64_t CSCTimingModel::globalBGCount()const{return uint64_t(channels_)*ranks_*bgs_;}
uint64_t CSCTimingModel::address(uint32_t g,uint32_t bank,uint32_t base,uint64_t burst){unsigned row=base,col=burst;return am_->addrGenSafe(g/bgs_,0,g%bgs_,bank,row,col);}
uint64_t CSCTimingModel::drain(){uint64_t before=cycle_;while(mem_->hasPendingTransactions()){mem_->update();cycle_++;}return cycle_-before;}
uint64_t CSCTimingModel::image(const CSCLayout&l,bool values,bool write,uint32_t bank,uint32_t base,const char*tag){for(uint32_t g=0;g<64;++g){auto&bytes=values?l.bg[g].values:l.bg[g].row_indices;for(uint64_t b=0;b<bytes.size()/32;++b)mem_->addTransaction(write,address(g,bank,base,b),tag,&burst_);}return drain();}
TimingStats CSCTimingModel::run(const CSCLayout&l,const ExecutionStats&e,bool result){validateLayout(l);TimingStats s;s.matrix_preload_bursts=(l.stats.physical_value_bytes+l.stats.physical_index_bytes)/32;s.matrix_preload_cycles=image(l,true,true,0,0,"CSC_PRELOAD_VALUE")+image(l,false,true,1,4096,"CSC_PRELOAD_INDEX");for(uint32_t g=0;g<64;++g){uint64_t n=(l.bg[g].x_slot_to_original_col.size()+7)/8;s.x_bursts+=n;for(uint64_t b=0;b<n;++b)mem_->addTransaction(false,address(g,2,8192,b),"CSC_X_LOAD",&burst_);}s.x_load_cycles=drain();s.value_bursts=e.value_burst_read_count;for(uint32_t g=0;g<64;++g)for(auto&d:l.bg[g].descriptors)for(uint32_t c=0;c<(d.nnz_count+7)/8;++c)mem_->addTransaction(false,address(g,0,0,d.value_offset_bytes/32+c),"CSC_VALUE_READ",&burst_);s.value_read_cycles=drain();s.row_index_bursts=e.row_index_burst_read_count;for(uint32_t g=0;g<64;++g)for(auto&d:l.bg[g].descriptors)for(uint32_t c=0;c<(d.nnz_count+7)/8;++c)mem_->addTransaction(false,address(g,1,4096,d.row_idx_offset_bytes/32+c),"CSC_ROW_INDEX_READ",&burst_);s.row_index_read_cycles=drain();if(result){s.result_bursts=(l.matrix.rows*4+31)/32;for(uint64_t b=0;b<s.result_bursts;++b)mem_->addTransaction(true,address(b%64,3,12288,b/64),"CSC_RESULT_WRITE",&burst_);s.result_cycles=drain();}s.kernel_resident_cycles=s.value_read_cycles+s.row_index_read_cycles+s.result_cycles;s.kernel_with_x_cycles=s.x_load_cycles+s.kernel_resident_cycles;s.end_to_end_simulated_cycles=s.matrix_preload_cycles+s.kernel_with_x_cycles;return s;}
}
