#include "csc/CSCDescriptorEngine.h"
#include "Callback.h"
#include "MultiChannelMemorySystem.h"
#include "SystemConfiguration.h"
#include "tests/KernelAddrGen.h"
#include <algorithm>
#include <cstring>
#include <stdexcept>
namespace csc_descriptor {
CSCDescriptorEngine::CSCDescriptorEngine(uint32_t bg,DRAMSim::PIMBlock*p,Submit s,Address a):global_bg_id_(bg),datapath_(p),submit_(std::move(s)),address_(std::move(a)){if(bg>=64||!p||!submit_||!address_)throw std::invalid_argument("CSC engine construction");}
bool CSCDescriptorEngine::descriptorValid(const CSCDescriptor&d)const{uint64_t physical=((uint64_t(d.nnz_count)+7)/8)*32;return d.global_bg_id==global_bg_id_&&d.nnz_count&&d.value_offset_bytes%32==0&&d.row_idx_offset_bytes%32==0&&d.x_slot<image_.packed_x->size()&&d.value_offset_bytes+physical<=image_.values->size()&&d.row_idx_offset_bytes+physical<=image_.row_indices->size();}
void CSCDescriptorEngine::validateLaunch()const{if(!image_.values||!image_.row_indices||!image_.descriptors||!image_.packed_x||!sink_)throw std::invalid_argument("null CSC launch view");}
void CSCDescriptorEngine::launch(const CSCBGImageView&v,std::vector<CSCPartial>*sink){if(busy_||tracker_.pending())throw std::logic_error("CSC engine already busy");image_=v;sink_=sink;validateLaunch();descriptor_pointer_=remaining_nnz_=chunk_offset_=chunk_index_=0;done_=false;flush_requested_=flush_completed_=false;error_code_=CSCError::NONE;error_.clear();counters_={};tracker_.reset();datapath_->resetSIMDCounters();busy_=true;state_=image_.descriptors->empty()?CSCDescriptorState::DONE:CSCDescriptorState::FETCH_DESCRIPTOR;if(state_==CSCDescriptorState::DONE){busy_=false;done_=true;}}
void CSCDescriptorEngine::fail(CSCError code,const std::string&s){if(state_==CSCDescriptorState::ERROR)return;error_code_=code;error_=s;busy_=false;done_=false;flush_completed_=false;state_=CSCDescriptorState::ERROR;}
bool CSCDescriptorEngine::issue(CSCRequestKind k,uint64_t off){if(tracker_.pending()||tracker_.completionReady()){counters_.stall_cycles_request++;return false;}uint64_t a=address_(global_bg_id_,k,off);if(!submit_(this,k,a)){tracker_.recordSubmitRejected();counters_.stall_cycles_backpressure++;return false;}tracker_.recordIssue(k,a,global_bg_id_/4,global_bg_id_);return true;}
bool CSCDescriptorEngine::onRequestComplete(unsigned c,uint64_t a,uint64_t cycle){if(!tracker_.complete(c,a,cycle))return false;if(hasFailed())tracker_.consumeCompletion();return true;}
void CSCDescriptorEngine::tick(){if(!busy_)return;counters_.busy_cycles++;counters_.total_execution_cycles++;
 switch(state_){
 case CSCDescriptorState::FETCH_DESCRIPTOR:current_=(*image_.descriptors)[descriptor_pointer_];if(!descriptorValid(current_)){fail(CSCError::MALFORMED_DESCRIPTOR,"malformed CSC descriptor at runtime");break;}remaining_nnz_=current_.nnz_count;chunk_offset_=chunk_index_=0;counters_.descriptor_fetches++;state_=CSCDescriptorState::LOAD_X;break;
 case CSCDescriptorState::LOAD_X:if(tracker_.completionReady()){tracker_.consumeCompletion();if(current_.x_slot>=image_.packed_x->size()){fail(CSCError::MALFORMED_DESCRIPTOR,"packed x changed while request was pending");break;}x_j_=(*image_.packed_x)[current_.x_slot];counters_.x_scalar_loads++;state_=CSCDescriptorState::FETCH_VALUE;}else if(!tracker_.pending()&&issue(CSCRequestKind::X_READ,uint64_t(current_.x_slot/8)*32))counters_.x_transactions++;else counters_.stall_cycles_request++;break;
 case CSCDescriptorState::FETCH_VALUE:if(tracker_.completionReady()){tracker_.consumeCompletion();std::memcpy(value_staging_.data(),image_.values->data()+current_.value_offset_bytes+chunk_offset_,32);state_=CSCDescriptorState::FETCH_ROW_INDEX;}else if(!tracker_.pending()&&issue(CSCRequestKind::VALUE_READ,current_.value_offset_bytes+chunk_offset_))counters_.value_transactions++;else counters_.stall_cycles_request++;break;
 case CSCDescriptorState::FETCH_ROW_INDEX:if(tracker_.completionReady()){tracker_.consumeCompletion();std::memcpy(index_staging_.data(),image_.row_indices->data()+current_.row_idx_offset_bytes+chunk_offset_,32);state_=CSCDescriptorState::WAIT_OPERANDS;}else if(!tracker_.pending()&&issue(CSCRequestKind::INDEX_READ,current_.row_idx_offset_bytes+chunk_offset_))counters_.index_transactions++;else counters_.stall_cycles_request++;break;
 case CSCDescriptorState::WAIT_OPERANDS:state_=CSCDescriptorState::SIMD_MUL;break;
 case CSCDescriptorState::SIMD_MUL:{valid_count_=std::min<uint32_t>(remaining_nnz_,8);DRAMSim::BurstType values,scalar;for(uint32_t i=0;i<8;i++){values.fp32Data_[i]=0;scalar.fp32Data_[i]=x_j_;result_staging_.fp32Data_[i]=-12345;}std::memcpy(values.fp32Data_,value_staging_.data(),valid_count_*4);auto before=datapath_->simdCounters();datapath_->mul(result_staging_,values,scalar,valid_count_);auto after=datapath_->simdCounters();counters_.invalid_lane_multiplies+=(after.invalid_lane_operand_reads-before.invalid_lane_operand_reads)+(after.invalid_lane_arithmetic_operations-before.invalid_lane_arithmetic_operations);counters_.invalid_lane_writes+=after.invalid_lane_destination_writes-before.invalid_lane_destination_writes;counters_.logical_mul_events++;counters_.total_chunks++;counters_.active_lanes+=valid_count_;counters_.available_lanes+=8;valid_count_==8?counters_.full_chunks++:counters_.tail_chunks++;state_=CSCDescriptorState::EMIT_PARTIALS;break;}
 case CSCDescriptorState::EMIT_PARTIALS:for(uint32_t i=0;i<valid_count_;i++){uint32_t row;std::memcpy(&row,index_staging_.data()+i*4,4);sink_->push_back({row,global_bg_id_,descriptor_pointer_,chunk_index_,i,result_staging_.fp32Data_[i]});counters_.generated_partials++;counters_.emitted_partials++;}state_=CSCDescriptorState::ADVANCE_CHUNK;break;
 case CSCDescriptorState::ADVANCE_CHUNK:remaining_nnz_-=valid_count_;chunk_offset_+=32;chunk_index_++;state_=remaining_nnz_?CSCDescriptorState::FETCH_VALUE:CSCDescriptorState::NEXT_DESCRIPTOR;break;
 case CSCDescriptorState::NEXT_DESCRIPTOR:descriptor_pointer_++;if(descriptor_pointer_<image_.descriptors->size())state_=CSCDescriptorState::FETCH_DESCRIPTOR;else finishWork();break;
 case CSCDescriptorState::DONE:if(tracker_.pending()||tracker_.completionReady()){fail(CSCError::INTERNAL_INVARIANT,"DONE with pending request");break;}busy_=false;done_=true;break;
 case CSCDescriptorState::FLUSHING:if(!tracker_.pending()&&!tracker_.completionReady()){state_=CSCDescriptorState::DONE;busy_=false;done_=true;flush_completed_=true;}break;
 case CSCDescriptorState::IDLE:case CSCDescriptorState::ERROR:break;}}
void CSCDescriptorEngine::finishWork(){if(flush_requested_){state_=CSCDescriptorState::FLUSHING;busy_=true;}else state_=CSCDescriptorState::DONE;}
void CSCDescriptorEngine::flush(){if(state_==CSCDescriptorState::ERROR)return;if(flush_requested_&&flush_completed_)return;flush_requested_=true;if(state_==CSCDescriptorState::IDLE||state_==CSCDescriptorState::DONE){flush_completed_=false;done_=false;busy_=true;state_=CSCDescriptorState::FLUSHING;}}
void CSCDescriptorEngine::reset(){if(tracker_.pending())throw std::logic_error("reset with pending request");tracker_.reset();busy_=done_=flush_requested_=flush_completed_=false;error_code_=CSCError::NONE;state_=CSCDescriptorState::IDLE;error_.clear();counters_={};}

struct CSCNativeExecution::Impl{std::shared_ptr<DRAMSim::MultiChannelMemorySystem>mem;std::unique_ptr<PIMAddrManager>addresses;DRAMSim::TransactionCompleteCB*read_cb=nullptr,*write_cb=nullptr;DRAMSim::BurstType burst;};
CSCNativeExecution::CSCNativeExecution():impl_(new Impl){impl_->mem=std::make_shared<DRAMSim::MultiChannelMemorySystem>("ini/HBM2_samsung_2M_16B_x64.ini","system_hbm_csc_fp32.ini",".","csc_native_m4",256*16);if(getConfigParam(UINT,"NUM_CHANS")!=16||getConfigParam(UINT,"NUM_RANKS")!=1||getConfigParam(UINT,"NUM_BANK_GROUPS")!=4||PIMConfiguration::getPIMPrecision()!=FP32)throw std::runtime_error("M4 requires 16ch/1rank/4BG/FP32");impl_->addresses.reset(new PIMAddrManager(16,1));impl_->read_cb=new DRAMSim::Callback<CSCNativeExecution,void,unsigned,uint64_t,uint64_t>(this,&CSCNativeExecution::readComplete);impl_->write_cb=new DRAMSim::Callback<CSCNativeExecution,void,unsigned,uint64_t,uint64_t>(this,&CSCNativeExecution::readComplete);impl_->mem->RegisterCallbacks(impl_->read_cb,impl_->write_cb,nullptr);for(uint32_t g=0;g<64;g++)blocks_.emplace_back(new DRAMSim::PIMBlock(FP32));for(uint32_t g=0;g<64;g++)engines_.emplace_back(new CSCDescriptorEngine(g,blocks_[g].get(),[this](auto*e,auto k,auto a){return submit(e,k,a);},[this](auto g,auto k,auto o){return addressFor(g,k,o);}));}
CSCNativeExecution::~CSCNativeExecution(){delete impl_->read_cb;delete impl_->write_cb;}
uint64_t CSCNativeExecution::addressFor(uint32_t g,CSCRequestKind kind,uint64_t offset){uint32_t bank=kind==CSCRequestKind::X_READ?2:(kind==CSCRequestKind::VALUE_READ?0:1);uint32_t base=kind==CSCRequestKind::X_READ?8192:(kind==CSCRequestKind::VALUE_READ?0:4096);unsigned row=base,col=offset/32;return impl_->addresses->addrGenSafe(g/4,0,g%4,bank,row,col);}
bool CSCNativeExecution::submit(CSCDescriptorEngine*e,CSCRequestKind,uint64_t a){if(failed_||outstanding_)return false;if(!impl_->mem->addTransaction(false,a,"CSC_NATIVE_M4",&impl_->burst))return false;outstanding_=e;outstanding_address_=a;return true;}
void CSCNativeExecution::readComplete(unsigned c,uint64_t a,uint64_t when){if(!outstanding_||a!=outstanding_address_||!outstanding_->onRequestComplete(c,a,when))throw std::logic_error("ambiguous M4 callback");outstanding_=nullptr;outstanding_address_=0;}
void CSCNativeExecution::launch(const std::array<CSCBGImageView,64>&v,uint32_t rows,uint64_t nnz){if(busy())throw std::logic_error("M4 execution busy");uint64_t descriptor_nnz=0;for(auto&bg:v){if(!bg.descriptors)throw std::invalid_argument("null M4 descriptor view");for(auto&d:*bg.descriptors)descriptor_nnz+=d.nnz_count;}if(descriptor_nnz!=nnz)throw std::invalid_argument("M4 descriptor NNZ mismatch");partials_.clear();rows_=rows;nnz_=nnz;cycle_=host_accumulations_=0;outstanding_=nullptr;failed_=flush_requested_=flush_completed_=false;error_code_=CSCError::NONE;failed_engine_=-1;error_message_.clear();for(uint32_t g=0;g<64;g++){engines_[g]->reset();engines_[g]->launch(v[g],&partials_);}launched_=true;}
void CSCNativeExecution::latchFailure(const CSCDescriptorEngine&e){if(failed_)return;failed_=true;error_code_=e.errorCode();error_message_=e.errorMessage();failed_engine_=int32_t(e.globalBG());}
void CSCNativeExecution::tick(){if(!launched_||isTerminal())return;impl_->mem->update();cycle_++;for(auto&e:engines_){if(failed_)break;e->tick();if(e->hasFailed())latchFailure(*e);}if(flush_requested_&&isDone())flush_completed_=true;}
bool CSCNativeExecution::busy()const{return launched_&&!isTerminal();}
bool CSCNativeExecution::hasPendingTransactions()const{return impl_->mem->hasPendingTransactions();}
bool CSCNativeExecution::hasUnconsumedCompletion()const{for(auto&e:engines_)if(e->tracker().completionReady())return true;return false;}
bool CSCNativeExecution::isTerminal()const{if(!launched_||outstanding_||impl_->mem->hasPendingTransactions()||hasUnconsumedCompletion())return false;if(failed_)return true;for(auto&e:engines_)if(!e->isTerminal())return false;return true;}
bool CSCNativeExecution::isDone()const{if(!isTerminal()||failed_)return false;for(auto&e:engines_)if(!e->isDone())return false;return true;}
void CSCNativeExecution::flush(){flush_requested_=true;if(!launched_)launched_=true;for(auto&e:engines_)e->flush();if(isDone())flush_completed_=true;}
void CSCNativeExecution::reset(){if(outstanding_||impl_->mem->hasPendingTransactions())throw std::logic_error("M4 reset with pending request");for(auto&e:engines_)e->reset();partials_.clear();launched_=failed_=flush_requested_=flush_completed_=false;rows_=0;nnz_=0;host_accumulations_=0;error_code_=CSCError::NONE;failed_engine_=-1;error_message_.clear();}
std::vector<float>CSCNativeExecution::hostAccumulate(){if(!isDone())throw std::logic_error("M4 accumulation before successful DONE");std::vector<double>s(rows_);host_accumulations_=0;for(auto&p:partials_){if(p.row_idx>=rows_)throw std::logic_error("M4 partial row range");s[p.row_idx]+=p.value;host_accumulations_++;}std::vector<float>y(rows_);for(size_t i=0;i<y.size();i++)y[i]=float(s[i]);return y;}
CSCExecutionCounters CSCNativeExecution::counters()const{CSCExecutionCounters t;for(auto&e:engines_){auto&c=e->counters();t.descriptor_fetches+=c.descriptor_fetches;t.x_scalar_loads+=c.x_scalar_loads;t.x_transactions+=c.x_transactions;t.value_transactions+=c.value_transactions;t.index_transactions+=c.index_transactions;t.logical_mul_events+=c.logical_mul_events;t.full_chunks+=c.full_chunks;t.tail_chunks+=c.tail_chunks;t.total_chunks+=c.total_chunks;t.active_lanes+=c.active_lanes;t.available_lanes+=c.available_lanes;t.invalid_lane_multiplies+=c.invalid_lane_multiplies;t.invalid_lane_writes+=c.invalid_lane_writes;t.generated_partials+=c.generated_partials;t.emitted_partials+=c.emitted_partials;t.stall_cycles_request+=c.stall_cycles_request;t.stall_cycles_backpressure+=c.stall_cycles_backpressure;t.busy_cycles+=c.busy_cycles;}t.host_accumulations=host_accumulations_;t.total_execution_cycles=cycle_;return t;}
}
